#!/usr/bin/env python3

import skilstak.colors as c

"""My super awesome hello world program."""

def print_plain(message):
    """prints <message> in plain text>"""
    print(message)

def print_color(message):
    """Prints hello in a random color each time"""
    print(c.rc() + message + "!" + c.reset)

def print_nyan(message):
    """Prints <message> forever"""
    while True:
        print(c.rc() + message , end=" ")

if __name__ == '__main__':
    print_nyan("Hello world")
    
