#!/usr/bin/env python3

import skilstak.colors as c

"""My super awesome hello world program."""

def print_plain(who="world"):
    """Simple prints hello to the screen

    Args:
        who (str): Who are we saying hello to
    """
    print("Hello " + who + "!")

def print_color(who="world"):
    """Prints hello in a random color each time"""
    print(c.rc() + "hello " + who + "!" + c.reset)

if __name__ == '__main__':
    who="world"
    option = ""
    if option 
