#!/usr/bin/env python3

""""Not yo grandma's hello world."""

import skilstak.colors as c
import time

def plain():
    """Clears the screen and prints 'Hello world'."""
    print(c.clear + c.rc() + "Hello world" + c.reset)

def multi():
    """prints 'Hello world' in multiple colors like a christmas tree (or Veags sign)."""
    while True:
        print(c.clear + c.multi("Hello world"))
        time.sleep(0.5)

def color():
    """Fills the screen with randomly colored 'Hello world's."""
    print(c.clear)
    while True:
        print(c.rc() + "Hello world" + c.reset, end=" ")

def hello(kind='plain'):
    """Main 'Hello world' function"""    
    try:
        if kind == 'color':
           color()
        elif kind.startswith('m'):
            multi()
        else:
            plain()        

    except KeyboardInterrupt:
        return

if __name__ == '__main__':
    from sys import argv
    option = " "

    if len(argv) == 2:
        

